name:                HOpenCL
version:             0.1.0.0

extra-source-files:
- README.md
- LICENSE

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- parsec
- syb

ghc-options:
- -Wall
- -Werror
- -Wincomplete-uni-patterns
- -Wincomplete-record-updates

when:
  - condition: os(linux)
    extra-libraries: OpenCL
  - condition: os(darwin)
    cpp-options: -DCALLCONV=ccall
    cc-options: "-U__BLOCKS__"
    frameworks: OpenCL
  - condition: os(windows)
    extra-libraries: opencl

library:
  source-dirs: src

executables:
  square-vector:
    main: Main.hs
    source-dirs: examples/square-vector
    dependencies: [base, HOpenCL]
    ghc-options: [-threaded]
